#!/bin/bash

echo "Start installing conky-theme"
echo "Copying conkyrc template..."
cp template conkyrc

echo "Moving conkyrc..."
mv conkyrc ~/.conkyrc

echo "Installing config..."
~/conky-yasno/scripts/config.sh

echo "Starting..."
conky
